In [1]:
import numpy as np

In [17]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?

array1 = np.array([[10, 8], [3, 5]])

array2 = np.linalg.inv(array1)

np.dot(array2, array1)

array([[1., 0.],
       [0., 1.]])

In [13]:
#2. 運用上列array計算特徵值、特徵向量?

w, v = np.linalg.eig(array1)

# eigenvalues

w

array([13.,  2.])

In [14]:
#2. 運用上列array計算特徵值、特徵向量?

w, v = np.linalg.eig(array1)

# eigenvectors

v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [18]:
#3. 運用上列array計算SVD?

np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))